# Generated by Django 5.1.6 on 2025-03-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_userprofile_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
