# Generated by Django 5.1.6 on 2025-03-03 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_1080p',
            field=models.FileField(blank=True, null=True, upload_to='videos/1080p'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_144p',
            field=models.FileField(blank=True, null=True, upload_to='videos/144p'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_240p',
            field=models.FileField(blank=True, null=True, upload_to='videos/240p'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_360p',
            field=models.FileField(blank=True, null=True, upload_to='videos/360p'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_480p',
            field=models.FileField(blank=True, null=True, upload_to='videos/480p'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_720p',
            field=models.FileField(blank=True, null=True, upload_to='videos/720p'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/originals'),
        ),
    ]
