# Generated by Django 5.1.6 on 2025-03-03 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0002_video_video_1080p_video_video_144p_video_video_240p_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
