# Generated by Django 5.1.6 on 2025-03-30 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0003_alter_video_id'),
    ]

    operations = [
    ]
