# Generated by Django 5.1.6 on 2025-04-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0007_video_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='genre',
            field=models.CharField(choices=[('action', 'Action'), ('drama', 'Drama'), ('sci-fi', 'Sci-Fi'), ('documentary', 'Documentary')], default='action', max_length=30),
        ),
    ]
